pub enum TileIndex {
    Empty = 0,
    DeadGrass = 1,
    DirtPath = 2,
    TileRosetteLight = 3,
    TileRosetteHeavy = 4,
    FineGrass = 5,
    FlowerGrass = 6,
    ThickGrass = 7,
    HerringTile = 16,
    TriangleTile = 17,
    CobbleNWCorner = 18,
    CobbleN = 19,
    CobbleNECorner = 20,
    LadderEnd = 21,
    PersonPriestRobe = 24,
    Person = 25,
    PersonSpear = 26,
    PersonSwordShield = 27,
    PersonHelmetSwordShield = 28,
    PersonHelmetSpearShield = 29,
}
