pub enum TileIndex {
    Empty = 0,
    GrassMixed = 1,
    PathDirt = 2,
    TileRosetteLight = 3,
    TileRosetteHeavy = 4,
    GrassFine = 5,
    GrassFlower = 6,
    GrassThick = 7,
    TileHerring = 16,
    TileTriangle = 17,
    CobbleNWCorner = 18,
    CobbleN = 19,
    CobbleNECorner = 20,
    LadderEnd = 21,
    PersonPriestRobe = 24,
    Person = 25,
    PersonSpear = 26,
    PersonSwordShield = 27,
    PersonHelmetSwordShield = 28,
    PersonHelmetSpearShield = 29,
    PersonArmor = 30,
    PersonHornedHelmetSwordShield = 31,
    TreeConiferFlat = 49,
    TreeConiferRough = 50,
    TreeDeciduous = 51,
    TreeDeciduousPair = 52,
    TreeDeciduousThick = 53,
    TreeJungle = 54,

}
